### ISSUE TITLE
NPM requirability mods

### ISSUE THREAD

**Issue by jahbini** [winterland1989/mui#1]
I've updated the build and require semantics for this package.  Please check-out my fork of mui to see if it fits your agenda --

For Example, in coffeescript,
{Collapse,Button,ButtonGroup}=require 'mui'

is what works.
BTW, I changed 'collaspe' into 'collapse'.  Was that OK?

**Comment by winterland1989** [comment]
I guess it's just not my taste, so i will leave it as it is now. But anyway thanks for using this lib.
